# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import time

from vllm import LLM, SamplingParams

enable_builtin_profiling = False

# Sample prompts.
prompts = [
    """You are a GPU performance optimization expert specializing in CUDA kernel development. Explain the complete process of optimizing a memory-bound GEMM (General Matrix Multiplication) kernel for NVIDIA GPUs. Start by describing how to analyze memory bandwidth utilization using NVIDIA Nsight Compute, including which metrics to monitor (DRAM bandwidth, L2 cache hit rates, memory coalescing efficiency). Then walk through the optimization steps: coalescing memory accesses, utilizing shared memory effectively, managing the register file, and applying blocking strategies to improve arithmetic intensity. Discuss the roofline model and how it guides optimization decisions by identifying whether a kernel is compute-bound or memory-bound. Include specific code patterns for memory access optimization, such as transposing data in shared memory to improve cache hit rates, and explain how bank conflicts in shared memory can degrade performance. Finally, explain when to use different CUDA APIs like cuBLAS, CUTLASS, or hand-optimized kernels, and provide insights on achieving 80-90% of theoretical peak performance for different matrix sizes and batch configurations.""",

    """Analyze the architectural differences between NVIDIA's compute capabilities (CC 7.0, 8.0, 9.0) and how these differences impact CUDA kernel design decisions. Discuss the evolution of streaming multiprocessor (SM) design, tensor core organization, memory hierarchy changes (L1, L2, shared memory sizes), and warp scheduling mechanisms. Explain how newer architectures improve hardware features like tensor cores with sparsity support, dynamic shared memory allocation, and improved memory bandwidth. For each generation, describe specific optimization techniques that leverage unique architectural features. Include examples of kernels that perform differently across architectures due to register file sizes, shared memory bandwidth, or warp scheduling. Discuss compatibility considerations when optimizing for multiple GPU generations, and explain how to write kernels that perform well across CC 7.0 through 9.0. Additionally, cover the implications of architectural changes on occupancy calculations, latency hiding strategies, and the theoretical peak performance (FP32, TF32, FP64, sparsity-enhanced) for each compute capability.""",

    """Create a comprehensive guide to utilizing shared memory effectively in CUDA kernels for transformer attention mechanisms. Start by explaining the limitations of global memory bandwidth for attention operations and how shared memory can accelerate these kernels. Discuss memory access patterns in multi-head attention, including the Q, K, V matrix multiplications and the softmax computation. Explain techniques for coalescing memory loads from global memory into shared memory, handling bank conflicts when accessing shared memory in specific patterns, and optimizing the shared memory layout for different attention implementations. Cover the distinction between static and dynamic shared memory allocation, and when to use each approach. Include strategies for managing the shared memory footprint when working with different sequence lengths and head dimensions. Discuss how to implement flash attention-style algorithms using shared memory tiling to reduce global memory accesses. Explain numerical stability considerations and how to organize computations to minimize precision loss. Finally, provide performance analysis techniques using Nsight Systems and Nsight Compute to measure shared memory effectiveness, cache hit rates, and identify remaining bottlenecks.""",

    """Explain the complete process of profiling and optimizing a batched GEMM operation across different batch sizes and matrix dimensions. Start with understanding the performance characteristics: how throughput changes as batch size increases, where memory bandwidth saturation occurs, and at what point compute becomes the limiting factor. Use the roofline model to predict performance and identify optimization targets for different problem sizes. Discuss how to use NVIDIA profiling tools to measure achieved bandwidth, arithmetic intensity, and utilization. Explain the differences between row-major and column-major layouts and their impact on memory coalescing. Cover kernel launch overhead considerations for small batches and strategies to reduce kernel call costs. Discuss when to fuse multiple operations (for example, batched GEMM followed by activation functions) versus keeping them separate. Include analysis of how different cuBLAS configurations (with or without batch stride parameters) affect performance for your specific use case. Explain GPU utilization patterns and how to achieve near-peak performance for matrix sizes ranging from small (64x64) to large (4096x4096) matrices. Provide concrete numbers and performance expectations for different hardware generations.""",

    """Develop a detailed strategy for implementing and optimizing a custom CUDA kernel for sparse matrix operations used in neural network inference. Begin with explaining the challenges of sparse matrix multiplication: irregular memory access patterns, load balancing across warps, and maintaining GPU occupancy with variable workloads. Compare different sparse matrix formats (CSR, COO, ELL) and their impact on kernel implementation and performance. Discuss how to choose an appropriate format based on sparsity pattern characteristics and hardware constraints. Explain techniques for handling irregular data access efficiently, including the use of warp-level primitives and synchronization patterns. Cover load balancing strategies to ensure even distribution of work across warps and blocks. Discuss how to maintain high occupancy despite irregular computation patterns. Include approaches for vectorizing operations when possible and handling edge cases near sparse matrix boundaries. Explain how to optimize shared memory usage in sparse operations, often with limited opportunities for data reuse. Discuss numerical precision requirements and how to maintain accuracy with sparse operations. Finally, cover profiling and debugging techniques specific to sparse kernels, including identifying load imbalance, memory access inefficiencies, and shared memory bottlenecks. Compare hand-optimized sparse kernels against library solutions like cuSPARSE.""",

    """Provide a comprehensive guide to CUDA memory management for large-scale deep learning model inference, covering all aspects from allocation strategies to memory optimization techniques. Discuss the memory hierarchy: global memory, unified memory with prefetching, pinned host memory, and device memory pools. Explain how to efficiently allocate and deallocate GPU memory for transformer models with variable sequence lengths, addressing fragmentation issues and memory leaks. Cover techniques for memory reuse, memory pooling strategies, and how to organize memory layouts for efficient prefetching. Discuss KV cache management in transformer inference, including strategies to reduce memory consumption through quantization, sparse storage, or sliding window approaches. Explain memory sharing between different pipeline stages and how to minimize redundant memory copies. Cover asynchronous memory operations using streams and events to overlap computation with data movement. Discuss techniques for batching inference requests and managing memory for dynamic batching scenarios. Include strategies for handling out-of-memory errors gracefully and implementing memory-aware scheduling. Explain unified memory features that can simplify memory management while maintaining performance through strategic prefetching. Finally, discuss memory profiling using NVIDIA tools to identify memory bottlenecks, measure memory efficiency, and optimize allocation patterns.""",

    """Analyze the design and optimization of a multi-GPU tensor distributed inference system with emphasis on communication overhead reduction and load balancing. Start by explaining different parallelization strategies: data parallelism, tensor parallelism, and pipeline parallelism, including their memory and communication tradeoffs. Discuss how to partition large models across multiple GPUs, considering computational load balance and communication patterns. Explain strategies for minimizing inter-GPU communication bandwidth requirements through techniques like gradient accumulation and overlapping communication with computation. Cover the use of NVIDIA Collective Communications Library (NCCL) for efficient multi-GPU operations, including reduce-scatter, all-reduce, and all-gather patterns. Discuss topology-aware communication scheduling that exploits the GPU interconnect topology. Explain techniques for hiding communication latency by overlapping with computation or by reorganizing computation order. Cover strategies for different GPU interconnect types: PCIe, NVLink, and high-speed ethernet. Discuss load balancing when models are unevenly partitioned across GPUs. Include performance modeling and profiling strategies to identify communication bottlenecks. Explain how different batch sizes and sequence lengths affect communication overhead. Finally, provide concrete recommendations for achieving near-optimal scaling efficiency for different model sizes and GPU configurations.""",

    """Create an in-depth guide to implementing and optimizing flash attention, a modern efficient attention mechanism for transformer models using GPU-friendly algorithms. Start with explaining the limitations of standard attention: O(N²) memory complexity and irregular memory access patterns that underutilize GPUs. Explain the key insight of flash attention: reformulating attention computation to improve memory efficiency through block-wise computation and recomputation. Walk through the mathematical foundations, including block-wise softmax computation and how to compute attention correctly with partial sums. Explain how to implement flash attention using shared memory to maintain intermediate results (softmax statistics) efficiently. Discuss how to organize the computation into tiles that fit in shared memory while maintaining numerical stability. Cover the handling of attention masks and causal masks in the flash attention framework. Explain how to adapt flash attention for multi-head attention and grouped-query attention variants. Discuss vectorization opportunities and how to achieve high memory bandwidth utilization. Include performance comparisons between standard attention, flash attention, and flash-2 variants. Explain how flash attention impacts the model's performance characteristics during inference, including improvements to throughput and memory bandwidth requirements. Cover integration with frameworks like PyTorch and practical considerations for production deployment.""",

    """Discuss comprehensive strategies for achieving high GPU utilization when running production inference serving for large language models on NVIDIA GPUs. Start with understanding the sources of GPU underutilization: kernel launch overhead, small batch sizes, memory fragmentation, and irregular workload patterns. Explain techniques for batching requests together to improve compute utilization while respecting latency constraints (using batch size accumulation and time-windowing strategies). Cover how continuous batching and iteration-level scheduling improve utilization compared to request-level scheduling. Discuss the tradeoffs between latency and throughput when tuning batch sizes and maximum waiting times. Explain how to use multiple streams effectively to overlap kernel execution and reduce serialization. Discuss how to structure inference pipelines to hide memory latencies through prefetching and speculative execution. Cover strategies for reducing memory footprint through model quantization, enabling larger effective batch sizes. Explain how to monitor and measure GPU utilization using profiling tools, identifying bottlenecks specific to your serving infrastructure. Discuss how different model architectures and shapes impact achievable utilization. Include practical recommendations for optimizing configurations across different hardware generations and providing resilient, low-latency inference services.""",

    """Provide a detailed technical guide to implementing custom CUDA kernels for layer normalization and group normalization operations in deep neural networks. Start by analyzing the computational challenges: how different normalization dimensions affect memory access patterns and thread block organization. Discuss the advantages and disadvantages of row-wise normalization (each thread processes one sample-feature pair) versus block-wise normalization (threads collaborate to compute statistics across features). Explain how to efficiently compute mean and variance using tree-reduction patterns within a warp and across a thread block. Cover techniques for achieving numerical stability when computing statistics, including Welford's online algorithm for variance calculation. Discuss how to handle batched operations efficiently, distributing threads across multiple samples to maximize occupancy. Explain how to optimize shared memory usage for intermediate statistics and how to minimize synchronization overhead. Cover the implementation of both forward and backward passes, including gradient computation for efficient backpropagation. Discuss vectorization opportunities when reading and writing data to optimize memory bandwidth. Explain how to handle different data layouts (NHWC versus NCHW) and their impact on kernel design. Include performance benchmarks and comparisons with library implementations like cuDNN. Finally, discuss production considerations like mixed-precision computation and gradient accumulation.""",

    """Analyze and explain techniques for optimizing softmax computation in CUDA, addressing both numerical stability and computational efficiency. Start with the mathematical challenges: preventing overflow and underflow when computing exponentials and achieving numerical precision. Explain the softmax-with-stable-log computation pattern that subtracts the maximum value before exponentiation. Discuss different reduction patterns for computing the maximum and sum values across a row: warp-level reductions, block-level reductions using shared memory, and techniques for reducing synchronization overhead. Cover how thread block organization affects memory access patterns and shared memory bank conflicts in reduction operations. Explain techniques for vectorizing softmax computation, especially when working with long sequences where multiple threads process different elements. Discuss how to implement log-softmax efficiently (often used in cross-entropy loss computation) without unnecessary intermediate computations. Cover batch softmax computation for attention mechanisms and classification layers, where thousands of softmax operations are computed simultaneously. Explain how to measure and optimize shared memory usage, register pressure, and arithmetic intensity for softmax kernels. Discuss specialized implementations for different problem sizes (short sequences where warp-level operations suffice, versus long sequences requiring block-level cooperation). Include comparisons with cuDNN implementations and recommendations for when to use libraries versus custom kernels. Finally, discuss mixed-precision softmax and how to maintain accuracy with reduced precision intermediate values.""",

    """Create a comprehensive guide to CUDA graph programming and optimization for inference workloads, explaining how CUDA graphs reduce overhead and improve GPU utilization. Start with understanding CUDA kernels' overhead components: CPU-GPU synchronization, kernel launch latency, and CPU scheduling overhead. Explain how CUDA graphs capture a sequence of operations into a reusable graph structure that can be replayed with minimal CPU involvement. Walk through the process of building graphs for static inference scenarios where input shapes don't change between iterations. Discuss how to structure graphs effectively to maximize the benefits of graph replaying: identifying static subgraphs, grouping operations efficiently, and minimizing synchronization points. Explain the limitations of CUDA graphs: the overhead of graph recording, the inflexibility when facing dynamic shapes, and how to design inference pipelines to work within these constraints. Cover techniques for handling dynamic batching within the constraints of static graphs, including graph specialization for common batch sizes. Discuss how CUDA graphs integrate with memory pooling for efficient resource management. Explain performance profiling and how to measure the speedup gained from graph usage. Include practical examples of graph construction for common operations: GEMM chains, activation functions, and layer-wise computations. Finally, discuss when CUDA graphs are beneficial versus overhead compared to dynamic kernel launches, and strategies for hybrid approaches combining graph and non-graph execution.""",

    """Explain the complete process of implementing a custom CUDA kernel for matrix transpose operations with various optimization strategies and their performance implications. Start with understanding why transpose operations are non-trivial on GPUs: naive implementations suffer from poor memory coalescing and excessive cache misses. Discuss the memory access pattern challenges: reading row-major input but writing column-major output (or vice versa) creates irregular access patterns. Explain the tile-based approach where each thread block handles a square tile of the matrix, loading it into shared memory and then writing it transposed. Cover how shared memory bank conflicts affect performance: when multiple threads access the same or predictable memory locations in shared memory, performance degrades. Discuss techniques for padding shared memory to avoid bank conflicts and the memory overhead tradeoff. Explain how to optimize for different matrix sizes: when matrix dimensions are powers of 2 (minimal bank conflicts) versus arbitrary dimensions (requiring conflict resolution). Cover vectorization strategies using float2 or float4 types to improve memory bandwidth utilization. Discuss how transposing block-wise versus element-wise affects register usage and occupancy. Explain the performance differences between in-place and out-of-place transposes. Include benchmarks for different matrix sizes and comparisons with cuBLAS implementations. Finally, discuss practical applications of optimized transpose kernels in neural networks where data layout changes are needed.""",

    """Provide an advanced guide to mixed-precision CUDA kernel design, focusing on FP32, FP16, TF32, and bfloat16 computation strategies for deep learning workloads. Start by explaining the numerical characteristics of different formats: FP32 (high precision, slow), FP16 (fast but prone to underflow), TF32 (good compromise), and bfloat16 (good numerical range, reduced precision). Discuss the hardware support on different GPU generations: tensor cores optimized for FP16 and TF32, INT8 support for quantization, and how to leverage these specialized units. Explain strategies for mixed-precision training and inference: accumulating in higher precision (FP32) while computing in lower precision (FP16) to balance speed and accuracy. Cover how to detect and prevent numerical instability in low-precision computation, including loss scaling techniques. Discuss the use of different precisions for different parts of computation: using FP16 for bulk computations but FP32 for reductions and statistics. Explain how to implement custom kernels that utilize tensor cores effectively for mixed-precision operations. Cover the interaction between precision choices and convergence during training. Discuss memory bandwidth savings when using lower precision (2x savings with FP16 versus FP32). Include practical recommendations for which layers benefit most from lower precision. Finally, discuss how to validate numerical correctness in mixed-precision kernels and handle edge cases where precision reduction causes problems.""",

    """Develop a detailed strategy for implementing and optimizing a custom CUDA kernel for batch normalization forward and backward passes in neural networks. Start with the mathematical operations: computing batch statistics (mean and variance) across samples and features, normalizing inputs, and then scaling/shifting with learned parameters. Discuss the memory access challenges: iterating over large tensors while maintaining cache locality. Explain two approaches: online statistics computation (reading the input data once but requiring running mean/variance accumulators) versus two-pass algorithms (one pass to compute statistics, another to normalize). Discuss the tradeoffs between register usage, shared memory, and global memory accesses. Cover techniques for parallelizing the statistics computation across multiple thread blocks and how to reduce partial statistics correctly. Explain how to maintain numerical stability when computing variance (using Welford's algorithm). Discuss the backward pass implementation: computing gradients with respect to inputs and parameters. Cover the interaction between batch norm and dropout during training, and how to structure the backward pass for efficient backpropagation. Explain specialized implementations for different data layouts (NCHW versus NHWC) and how layout affects occupancy and memory coalescing. Include how to implement fused batch norm + activation kernels (e.g., batch norm + ReLU) to reduce kernel launch overhead. Finally, discuss synchronized batch norm for distributed training and numerical considerations.""",

    """Create a comprehensive guide to CUDA dynamic parallelism and its applications in recursive algorithms, tree-based computations, and irregular workloads. Start by explaining what dynamic parallelism is: the ability of device code to launch new kernels without CPU involvement. Discuss the overhead of dynamic kernel launches and when this overhead is justified by improved load balancing or computational efficiency. Cover the execution model: how child grids are scheduled and managed relative to parent grids, synchronization semantics, and memory consistency. Explain practical applications: tree traversal, graph processing, recursive algorithms (binary search, quicksort partitioning), and workload redistribution for irregular problems. Discuss how to structure dynamically parallel kernels to maximize efficiency: balancing overhead with reduced CPU-GPU synchronization. Cover host-side CUDA graph programming as an alternative for structured recursive computations. Explain how to debug and profile dynamic kernels: understanding when child kernels execute and how resource constraints affect nesting. Discuss stack management and how recursion depth impacts GPU memory. Include comparisons between dynamic parallelism and explicit CPU-side loop launching for different problem characteristics. Discuss when dynamic parallelism helps (handling load imbalance) versus when it hurts (excessive synchronization overhead). Finally, provide concrete code examples and performance analysis for real-world applications.""",

    """Explain comprehensive strategies for implementing efficient warp-level primitives and operations in CUDA, leveraging warp-intrinsic instructions for high-performance computing. Start by explaining warp fundamentals: 32 threads executing in lockstep (on modern NVIDIA GPUs), and how this enables efficient communication between threads. Discuss shuffle operations that allow threads within a warp to exchange data without shared memory, reducing latency and eliminating bank conflicts. Explain warp-level reduction patterns: how to compute sum, max, min efficiently using shuffle operations. Cover the distinction between intrinsic instructions available before and after NVIDIA's Ampere generation regarding thread shuffling and masked operations. Discuss how to implement tree reductions across a warp for different problem sizes and reduction operations. Explain warp-level scan (prefix sum) operations and their applications in parallel algorithms. Cover how to combine warp-level operations into thread block operations: how to integrate warp reductions into block-level tree reductions. Discuss the performance advantages: reduced shared memory usage, fewer synchronization points, and lower latency communication. Include practical examples: warp-level sorting, segmented reductions, and histogram computation. Explain how to compose complex algorithms from warp primitives. Finally, discuss how to profile and measure the efficiency of warp-level primitives and when they outperform shared memory-based approaches.""",

    """Provide an advanced technical analysis of CUDA event-based synchronization and stream management for overlapping computation with memory transfers and kernel execution. Start with explaining CUDA streams: independent queues of operations that can execute concurrently (subject to hardware constraints). Discuss how to create, manage, and destroy streams efficiently to avoid resource leaks. Explain events as synchronization points between streams and how to measure time between events. Cover the most common pattern: overlapping a kernel executing on stream 0 with a memory transfer on stream 1, enabling pipelining of computation and data movement. Discuss host-device synchronization and when it's necessary (avoiding unnecessary synchronization that stalls the GPU). Explain how to structure computations for optimal overlap: identifying which operations can run concurrently and organizing streams accordingly. Cover potential hazards: data dependencies between kernels requiring explicit synchronization, and race conditions when operations access the same memory regions. Discuss the hardware limitations to overlap: the number of streams that can be truly concurrent, depending on GPU architecture. Explain how to use events to measure and profile stream execution, identifying bottlenecks in overlapping strategies. Include practical examples: pipelined data loading, multi-kernel execution, and asynchronous memory operations. Discuss how to debug stream-related issues and race conditions. Finally, explain advanced stream features like stream priorities and stream callbacks.""",

    """Develop a comprehensive guide to implementing and optimizing reduction operations in CUDA for computing aggregates (sum, min, max, custom operators) across large arrays. Start by explaining the computational challenge: reducing billions of elements to a single value while maintaining high GPU utilization. Discuss different reduction strategies: single-block reductions (limited to arrays fitting one block's shared memory), multi-block reductions (processing data in chunks), and hierarchical reductions (multiple passes over different GPU regions). Explain the memory and computational tradeoffs of each approach. Cover warp-level reduction using shuffle operations for the final reduction within a warp. Discuss how to implement tree-style reductions within a thread block using shared memory and synchronization. Explain techniques for ensuring correctness in floating-point reductions: how to maintain numerical stability and consistency. Cover specializations for different reduction operators: simple summation (highly parallel), or more complex custom operators. Discuss how to optimize for different data types: FP32, FP64, INT32. Cover the impact of data layout on reduction efficiency: coalescing memory accesses during the reading phase. Explain how to measure and optimize register usage and occupancy. Include comparisons with thrust reductions and library implementations. Finally, discuss how reductions are used in neural networks (computing loss functions, gradient statistics) and how optimization in this area impacts overall training speed.""",

    """Explain the complete process of profiling CUDA kernels using NVIDIA Nsight Compute, with focus on identifying and eliminating performance bottlenecks in compute-intensive workloads. Start with understanding Nsight Compute's architecture: how it instruments GPU code at the hardware level to collect detailed metrics without significant overhead. Discuss the setup process: configuring profiling settings, understanding kernel filtering, and baseline profiling captures. Walk through interpreting key metrics: SM utilization, warp occupancy, memory bandwidth achieved versus theoretical peak, cache hit rates (L1, L2), shared memory efficiency, and register pressure. Explain how to identify specific bottlenecks: if peak throughput isn't achieved, is the kernel memory-bound (waiting for memory) or compute-bound (waiting for compute units)? Cover the roofline analysis in Nsight Compute: plotting achieved throughput against arithmetic intensity to visualize performance relative to hardware limits. Discuss common bottlenecks: memory coalescing issues, bank conflicts in shared memory, register spillage, insufficient occupancy, and compute instruction latency hiding. Explain how to drill down into specific operations: identifying which memory operations are slow, where synchronization overhead accumulates, which instructions contribute most to execution time. Cover advanced metrics: tensor core utilization (for kernels using specialized math units), latency metrics, and instruction throughput. Include practical debugging workflow: capturing metrics for suspicious kernels, forming hypotheses about bottlenecks, modifying code, and re-profiling to verify improvements. Finally, discuss profiling best practices and common pitfalls in interpretation.""",

    """Create an in-depth guide to CUDA memory coalescing and cache behavior for optimizing global memory access patterns. Start with explaining memory coalescing: how consecutive threads access consecutive memory addresses, which can be serviced by a single memory transaction, versus scattered accesses requiring multiple transactions. Discuss the memory bus width (128 bytes for typical loads), and how coalesced accesses minimize the number of bus transactions needed. Explain how to identify and fix coalescing issues: transposing data access patterns, reorganizing thread assignments, or adjusting matrix layout. Cover the impact of thread block dimensions on coalescing: 1D thread blocks versus 2D blocks for 2D data processing. Discuss cache behavior: L1 cache line size (128 bytes), L2 cache characteristics, and how to improve cache hit rates. Explain the difference between access patterns that miss the L1 cache (requiring L2 access) versus patterns that hit: regular, predictable strides benefit caches. Cover bank conflicts in shared memory (a different but related concept): when multiple threads access shared memory in a pattern that creates collisions. Discuss how data layout affects both global memory coalescing and shared memory efficiency: row-major versus column-major matrices. Explain techniques for optimizing complex access patterns using transposition in shared memory. Include practical examples and measurements showing how coalescing optimization improves bandwidth. Finally, discuss modern GPU features like L1 cache improvements on newer architectures.""",

    """Provide a comprehensive technical analysis of tensor core utilization and how to leverage tensor cores for high-performance matrix operations in CUDA. Start by explaining what tensor cores are: specialized hardware units that compute 16x16x16 matrix multiplications in a single operation across different precision formats. Discuss their evolution: introduction on Volta, improvements on Turing, and enhancements on Ampere and Hopper architectures. Explain the WMMA (Warp Matrix Multiply Accumulate) API: how to use it directly in custom kernels. Discuss fragment organization: how tensor cores work with 16x16 sub-matrices and how threads in a warp split responsibility. Cover different numeric precisions: FP16 input with FP32 accumulation (high precision, good for training), FP16 input with FP16 accumulation (faster, lower precision), and TF32 variants. Explain the constraints of tensor core usage: input matrix dimensions must be multiples of 16, and memory layouts must match tensor core expectations. Discuss how to structure kernels to maximize tensor core utilization: organizing computations into 16x16 blocks, managing register usage for fragment storage. Cover the integration of tensor cores with shared memory for efficient data staging. Explain performance vs. cuBLAS: when custom tensor core kernels outperform general-purpose BLAS libraries. Include practical examples: implementing blocked matrix multiplication, batched operations, and mixed-precision computation. Finally, discuss how deep learning frameworks leverage tensor cores and how to write efficient custom kernels with this hardware.""",

    """Develop a detailed guide to implementing atomic operations in CUDA, understanding their performance implications, and strategies for minimizing contention. Start by explaining atomic operations: instructions that guarantee read-modify-write sequences complete atomically without interruption from other threads. Discuss different atomic operation types: atomicAdd (most common), atomicMin, atomicMax, atomicCAS (compare-and-swap), and custom reduction operators. Explain the performance cost: atomic operations serialize when multiple threads access the same memory location, causing contention. Discuss hardware implementation: how atomic operations are queued and processed, and why contention degrades performance dramatically. Explain strategies for reducing contention: partitioning data to eliminate concurrent atomic access to the same locations, using atomic operations on local (register) copies followed by final synchronization, or redesigning algorithms to avoid shared state. Cover warp-level atomics as a more efficient alternative when possible. Discuss how to measure contention in profilers: identifying atomic bottlenecks. Explain use cases where atomic operations are unavoidable: histogram computation, graph algorithms, and sparse tensor operations. Discuss alternatives to atomics: privatization (each thread maintains local accumulators, merged later), reduction patterns (tree-structured merging), or sorting-based approaches. Include specific optimization strategies for common patterns: reducing histogram computation overhead, accelerating graph traversals with atomics. Finally, discuss when atomic operations are acceptable (atomics on a small number of locations) versus problematic (thousands of threads atomically updating the same location).""",

    """Explain advanced CUDA debugging techniques for identifying and resolving common issues: race conditions, memory corruption, incorrect results, and performance degradation. Start with understanding CUDA error checking: using cudaGetLastError() and the CUDA error API to catch runtime errors. Discuss compute-sanitizer (formerly cuda-memcheck): detecting out-of-bounds memory access, uninitialized reads, and invalid memory operations. Explain how to use compute-sanitizer with different detection options: memory checking, race condition detection, and shared memory verification. Discuss how to debug incorrect computation: instrumenting kernels with printf statements (available on modern GPUs), reducing the problem to minimal test cases, and comparing against CPU reference implementations. Cover synchronization-related bugs: deadlocks from improper barrier synchronization, race conditions from missing __threadfence() calls, and convergence issues from thread divergence. Explain how to use NVIDIA's visual profiler for in-depth analysis: identifying stalls, synchronization overhead, and warp execution patterns. Discuss kernel crash debugging: handling invalid global memory access (often causes silent failures without clear error messages). Cover debugging in heterogeneous environments: ensuring CPU-GPU synchronization is correct, checking CPU-GPU data consistency. Include strategies for numerical debugging: tracking numerical stability, identifying precision-related issues, and validating results against reference implementations. Finally, discuss best practices: writing testable kernel code, maintaining debug builds with assertions, and continuous validation against golden reference outputs.""",

    """Create a comprehensive guide to implementing and optimizing prefix sum (scan) operations in CUDA, including both inclusive and exclusive variants. Start with explaining prefix sum: computing cumulative sums where each output position contains the sum of all elements up to that position (or up to but not including for exclusive scan). Discuss applications: array compaction, stream compaction for sparse data, parallel partition operations, and cumulative distribution functions. Explain the computational challenge: unlike reductions where only the final value matters, scan operations require all intermediate values, making parallelization non-trivial. Discuss sequential scan versus parallel approaches: Blelloch's scan algorithm is work-efficient but complex. Walk through the Kogge-Stone scan algorithm: efficient for GPUs with good parallelism but more work. Explain implementation using shared memory for small scans, and hierarchical approaches for large arrays. Cover how to implement single-pass scans and multi-level hierarchical scans. Discuss optimizations: using shuffle operations for warp-level scans, reducing synchronization overhead. Explain the implementation of segmented scans: independent scans for different segments (useful for processing multiple arrays simultaneously). Cover applications in neural networks: computing attention weights via normalization, histogram equalization. Discuss how modern frameworks implement scan (e.g., Thrust library). Include performance comparisons and benchmarks. Finally, explain how scan operations integrate into more complex algorithms for GPU computing.""",

    """Provide a detailed technical analysis of register usage optimization in CUDA kernels, balancing occupancy with performance. Start by explaining registers: per-thread storage managed by the GPU hardware, extremely fast but limited in quantity (up to 255 registers per thread on modern GPUs). Discuss how high register usage reduces occupancy: if each thread uses many registers, fewer threads can reside on an SM simultaneously, limiting parallelism. Explain the tradeoff: lower register usage allows higher occupancy (more threads, better latency hiding), but excessive register usage forces spills to global memory (extremely slow). Cover how to measure register usage: using nvcc compile flags, or inspecting kernel assembly code. Discuss techniques for reducing register pressure: limiting temporary variables, using shared memory instead of registers for intermediate storage, and careful data layout. Explain how compilers optimize register allocation and when to use pragmas to guide compilation. Discuss the distinction between register pressure from local variables versus registers used by compiler-generated code (e.g., loop counters). Cover how different optimization levels and compilation flags affect register allocation. Include practical examples: comparing high-occupancy kernels (low registers, many threads) versus low-occupancy kernels (high registers, fewer threads) and measuring performance in both cases. Discuss use cases where higher register usage is justified by reducing memory accesses. Finally, explain how to profile register usage and understand its impact on kernel performance.""",

    """Explain the implementation and optimization of parallel sorting algorithms in CUDA, addressing both small-batch and large-batch scenarios. Start with discussing sorting network approaches like bitonic sort: simple to parallelize, work-efficient, but with high communication overhead. Cover merge sort: better for GPUs with improved cache behavior but higher memory bandwidth requirements. Discuss radix sort: often fastest for certain data types, avoiding comparisons entirely. Walk through implementing bitonic sort: explaining the sorting network structure, how to parallelize comparisons, and optimizing for GPU execution with thread block organization. Discuss optimizations for small batches (fitting in shared memory) versus large batches requiring multiple kernel passes and global memory. Explain how to handle different data types: integers (straightforward), floats (special handling for NaN and sign), and custom key-value pairs. Cover sorting by key and secondary sorts. Discuss the tradeoff between work (number of comparisons performed) and depth (critical path length). Explain how to compare GPU sorting against library implementations (cuThrust) and identify when custom implementations provide value. Cover applications in neural networks: sorting for top-k selection (beam search), computing order statistics, and attention normalization. Discuss numerical stability considerations for floating-point sorting. Finally, include benchmarks and practical recommendations for different data sizes and GPU configurations.""",

    """Develop a detailed guide to implementing custom CUDA kernels for efficient image processing operations (convolution, pooling, filtering) with GPU optimization. Start by explaining memory access patterns in image processing: neighborhoods of data accessed together, strided accesses, and potential for cache exploitation. Discuss how image dimensions affect thread block organization and memory coalescing: tall images versus wide images, and standard approaches like 2D thread blocks for 2D data. Explain convolution operations: sliding a filter kernel across an image, computing weighted sums. Cover both forward pass (computing convolution) and backward pass (gradient computation). Discuss how shared memory accelerates convolution by loading neighborhoods efficiently. Explain techniques for handling image boundaries: padding strategies (zero-padding, reflection, replication) and how they affect memory access. Cover optimizations specific to common filters: separable 2D convolutions as consecutive 1D operations (faster with better cache reuse). Discuss pooling operations: max pooling and average pooling, which have different communication patterns. Include vectorization strategies: processing multiple pixels or channels in parallel. Explain how to optimize for different data layouts (NHWC versus NCHW) and their impact on coalescing. Discuss specialized hardware: how to leverage tensor cores for large-scale convolutions. Finally, include comparisons with optimized libraries like cuDNN and recommendations for when custom kernels are beneficial.""",

    """Explain the complete process of implementing quantization-aware training kernels in CUDA, supporting efficient low-bit neural network training. Start with understanding quantization: mapping high-precision values to low-bit representations (INT8, INT4) to reduce memory and computation. Discuss quantization schemes: uniform quantization (linear mapping), non-uniform quantization, and simulated quantization (training in low-bit precision). Explain the challenge of training with quantization: gradients through quantization functions are non-smooth, requiring careful numerical handling. Discuss straight-through estimators: approximating gradient flow through quantization operators. Walk through implementing forward passes: scaling high-precision activations and weights to low-bit representations. Explain backward passes: computing gradients with respect to scale factors and original values. Cover special handling for per-channel versus per-tensor quantization: affecting memory layout and computation granularity. Discuss how to maintain numerical stability when using low-bit precision for gradient accumulation. Explain techniques for learning optimal scale factors: optimizing quantization parameters during training. Cover the interaction between quantization and batch normalization, discussing fused operations. Explain how gradients of scale factors are computed and accumulated. Include practical challenges: handling activation quantization in backpropagation, per-layer quantization scheduling. Discuss integration with existing training frameworks. Finally, discuss how quantization affects convergence and accuracy, and strategies for minimizing the accuracy gap.""",

    """Create a comprehensive technical guide to NVIDIA's CUTLASS library: understanding its design, how to use CUTLASS kernels, and how to implement custom optimized operations using CUTLASS templates. Start by explaining CUTLASS's motivation: providing highly optimized, portable matrix operation primitives. Discuss the architecture: the building blocks (GEMM, CONV) and how they compose. Explain the abstraction layers: high-level convenience APIs versus low-level composition of building blocks. Discuss thread blocks, warps, and thread-level abstractions for matrix computations. Cover how CUTLASS exposes different precision formats and tensor core utilization. Explain the template parameters and how they affect performance: tile sizes, memory layouts, compute and memory data types. Discuss how to instantiate CUTLASS kernels for specific use cases: problem sizes, data types, and layouts. Cover comparison with cuBLAS: when CUTLASS provides advantages (custom operations, better integration, lower overhead) versus using established libraries. Explain how to write custom operations using CUTLASS primitives: composing CUTLASS kernels for operations not directly provided. Discuss profiling CUTLASS kernels and understanding where time is spent. Include practical examples: implementing batched GEMM, strided GEMM, and tensor contraction operations using CUTLASS. Finally, discuss integration with deep learning frameworks and how CUTLASS accelerates real-world applications.""",

    """Provide an advanced guide to handling numerical precision and stability in GPU-accelerated neural network training and inference. Start by explaining floating-point representation: IEEE 754 standards for FP32, FP16, and BF16, including how precision differs. Discuss sources of numerical instability: loss of significance in subtraction, catastrophic cancellation, and accumulation of rounding errors. Explain how GPU operations (parallel reductions, atomic additions) can introduce different rounding error patterns than sequential CPU computation. Discuss mixed-precision training: using FP16 for computations (faster) but FP32 for accumulation (stability). Explain loss scaling: scaling loss before backpropagation to utilize FP16 range, then unscaling gradients (critical for preventing gradient underflow). Cover gradient accumulation: splitting batches into sub-batches to reduce memory pressure while maintaining stable gradient accumulation. Discuss layer-wise gradient normalization for stability across deep networks. Explain how batch normalization affects numerical stability and how to implement it carefully for different precisions. Cover numerical issues specific to attention mechanisms: computing softmax with large exponents, managing precision in normalization. Discuss validation strategies: comparing GPU results against double-precision CPU baselines, detecting anomalies like NaN propagation. Include techniques for debugging precision issues: tracking value ranges, detecting underflow/overflow. Finally, discuss tradeoffs between speed (lower precision) and stability (higher precision), and practical guidelines for different scenarios.""",

    """Explain the design and optimization of custom CUDA kernels for efficient sparse neural network operations, focusing on structured and unstructured sparsity patterns. Start by understanding sparsity: networks where many weights or activations are zero, enabling computational savings. Discuss structured sparsity (e.g., block-wise sparsity, channel pruning) where zero patterns are regular, enabling simpler GPU utilization. Explain unstructured sparsity: arbitrary zeros, requiring irregular memory access patterns and sophisticated algorithms. Cover different sparse matrix formats: CSR (Compressed Sparse Row), COO (Coordinate), ELL (Ellpack), and their GPU implementation implications. Discuss matrix multiplication with sparsity: how sparse inputs and outputs affect computation and memory requirements. Explain pruning strategies: determining which weights to zero while maintaining accuracy. Cover the computational benefits: skipping operations on zero values (though detecting and skipping can be expensive). Discuss how sparse operations interact with hardware: tensor cores with sparsity support (Ampere and later), which require structured sparsity patterns. Explain strategies for exploiting sparse kernels: how to organize computation to benefit from sparsity. Discuss specialized libraries like cuSPARSE and when custom kernels provide advantages. Cover applications: neural network inference (reducing computation and memory bandwidth), sparse attention mechanisms, and sparse graph neural networks. Finally, discuss profiling sparse operations: measuring actual speedup and identifying when sparsity overhead exceeds benefits.""",

    """Develop a comprehensive guide to implementing and optimizing gather and scatter operations in CUDA, handling irregular memory access patterns. Start by explaining gather: reading data from memory using indices that may be non-sequential, and scatter: writing data to memory locations specified by indices. Discuss applications: array indexing, table lookups, histogram computation, and graph operations. Explain the memory access challenge: irregular index patterns prevent memory coalescing, causing inefficient cache behavior. Discuss different optimization strategies: sorting indices to improve locality, caching frequently accessed values, or using shared memory to stage data. Cover techniques for handling data dependencies: ensuring correctness when multiple indices reference the same memory location. Explain how to implement efficient gather with proper memory coalescing when possible: organizing indices to improve access patterns. Discuss specialized hardware features for gather: hardware texture caches (deprecated on modern GPUs) versus software solutions. Cover the performance characteristics: identifying bottlenecks through profiling. Explain techniques for handling large index arrays: multi-pass approaches, hierarchical methods. Include applications in neural networks: gathering embeddings, implementing gather layers, and irregular memory access patterns in sparse operations. Discuss how to combine gather and scatter for complex operations like permutation layers. Finally, include benchmarking and practical recommendations for optimizing these commonly-needed but challenging operations.""",

    """Explain comprehensive strategies for optimizing tensor contraction operations in CUDA, critical for deep learning and scientific computing. Start with understanding tensor contractions: general multi-dimensional array operations that generalize matrix multiplication. Discuss the complexity: not all tensor operations can be expressed as simple matrix multiplications. Explain how to reformulate arbitrary tensor contractions as matrix multiplications through reshape and transpose operations. Discuss the performance implications: different contraction orderings lead to different memory access patterns and cache behavior. Cover Einsum (Einstein summation): a notation for expressing tensor contractions, and how to implement efficient Einsum kernels. Explain strategies for orchestrating contractions: fusing multiple operations to reduce memory movement. Discuss how to use CUTLASS and GEMM-based approaches for tensor contractions. Cover the role of high-level libraries: TensorFlow's contraction operations, PyTorch's einsum. Explain memory layout implications: managing tensor strides and how they affect kernel design. Discuss numerical stability in chained contractions. Include profiling and optimization strategies: identifying the computational bottleneck in complex operations. Explain how to handle variable-size tensors and dynamic shapes. Finally, discuss advanced techniques like algorithmic transformations that reduce operation count, and how GPU implementations enable practical use of these techniques.""",

    """Create a detailed technical guide to implementing custom CUDA kernels for dropout operations, both forward and backward passes, with numerical considerations. Start by understanding dropout: randomly zeroing activations during training to prevent overfitting, while scaling remaining values. Discuss the challenge: maintaining numerical correctness despite random bit generation, ensuring consistency between forward and backward, and handling different seeding strategies. Explain pseudo-random number generation on GPUs: how to generate high-quality random numbers efficiently. Discuss seeding strategies: global seeds that ensure reproducibility across runs, versus local thread-specific seeds that enable parallel randomness. Explain how to implement dropout: generating random masks efficiently, applying scaling factors. Cover synchronized versus unsynchronized dropout: subtle differences in which randomness is used in backward pass. Discuss how to store random states: either regenerating random numbers in backward (more memory efficient) or storing the forward random state (simpler but requires memory). Explain the backward pass: how gradients flow through the dropout operation (apply the same mask from forward). Discuss numerical considerations: dropout interacts with batch normalization (where it's applied), and gradient scaling (ensuring gradient magnitudes are appropriate). Cover optimizations: fusing dropout with other operations (e.g., dropout + activation). Include how to handle variable dropout rates and per-element dropout probability. Discuss comparisons with library implementations (cuDNN). Finally, explain common pitfalls: incorrect mask generation, missing scaling factors, and gradient inconsistencies.""",

    """Provide an in-depth analysis of implementing efficient cumulative loss computation for training pipelines in CUDA, including gradient accumulation and numerical stability. Start by explaining why custom kernels are needed: standard approaches suffer from atomicAdd bottlenecks when accumulating loss across many threads. Discuss the challenge: computing loss from millions of predictions requires aggregating to a single value, and naive reduction creates bottlenecks. Explain strategies for efficient reduction: the tree-reduction pattern, hierarchical reduces. Discuss gradient accumulation: splitting large batches into smaller sub-batches, computing losses independently, then accumulating gradients. Cover how to structure kernels for this pattern: computing per-batch loss without synchronizing, then merging. Explain numerical stability: how floating-point errors accumulate during gradient accumulation, and strategies to minimize them. Discuss the use of higher-precision accumulators (FP32 or FP64) for loss accumulation even if using FP16 for computation. Explain how loss computation integrates with mixed-precision training: scaling losses appropriately, unscaling gradients. Cover optimization: fusing loss computation with other operations (e.g., softmax + cross-entropy). Discuss distributed training considerations: how loss reduction changes across multiple GPUs. Include practical implementation: how modern frameworks (PyTorch, TensorFlow) structure loss accumulation. Finally, discuss how to profile and optimize loss computation, identifying whether atomicAdd or other operations are the bottleneck.""",

    """Explain the complete process of implementing and optimizing activation function kernels in CUDA for neural networks, covering forward and backward passes. Start with common activation functions: ReLU, GELU, Swish, and others, discussing their mathematical properties and computational requirements. Explain the forward pass: element-wise operations that are embarrassingly parallel but require careful memory access optimization. Discuss how to vectorize activation functions: processing multiple elements per thread to improve arithmetic intensity. Cover backward passes: computing gradient through activation functions, often involving the forward pass output or intermediate values. Explain how to fuse activation kernels with preceding operations (e.g., GEMM + activation) to reduce kernel launch overhead and improve memory reuse. Discuss numerical stability: handling extreme values in exponentiation (GELU), and maintaining precision. Explain special cases: ReLU backward (only propagates positive gradients), which can be implemented very efficiently. Cover how to handle different data types and layouts. Discuss memory coalescing: how element-wise operations must be structured to achieve good memory bandwidth. Include optimization strategies: reducing register pressure, improving cache hit rates. Explain how activation functions behave differently with mixed-precision computation. Discuss profiling and benchmarking activation kernels. Finally, include comparisons with library implementations like cuDNN and recommendations for when custom kernels provide value.""",

    """Develop a comprehensive guide to CUDA stream callbacks and their applications in scheduling, asynchronous work, and CPU-GPU synchronization. Start by explaining stream callbacks: functions executed on the host CPU when all previously launched operations on a stream complete. Discuss how callbacks provide asynchronous notification without GPU-CPU synchronization overhead of explicit CPU-GPU barriers. Explain applications: scheduling dependent operations that can't be expressed as GPU kernels, checking results without blocking, and coordinating multi-GPU workloads. Discuss the semantics: callback execution occurs at the driver level, not necessarily on the main thread, and careful handling is needed. Cover how to use callbacks for dynamic kernels: launching new work based on GPU computation results without waiting for the GPU. Explain how callbacks integrate with other synchronization mechanisms: events, explicit synchronization. Discuss limitations: callbacks can't directly affect GPU operations already queued, so careful sequencing is necessary. Include practical examples: using callbacks to implement conditional kernel launches, adaptive batch sizing based on intermediate results, and asynchronous result collection. Cover debugging and profiling: understanding when callbacks execute relative to GPU operations. Discuss how callbacks interact with multiple streams and their ordering guarantees. Finally, explain best practices: keeping callbacks lightweight, avoiding unnecessary CPU-GPU synchronization, and structured use of callbacks versus explicit event-based synchronization.""",

    """Explain implementation strategies for efficient bidirectional communication between CPU and GPU in CUDA for interactive and adaptive applications. Start by discussing the challenge: CPU-GPU data movement is expensive and often becomes a bottleneck. Discuss different transfer mechanisms: synchronous transfers (blocking), asynchronous transfers (non-blocking), and pinned memory (allowing faster DMA transfers). Explain how to minimize transfer overhead: batching small transfers into larger ones, overlapping transfers with computation using multiple streams, and using persistent kernels for continuous work. Discuss data organization: how to arrange CPU memory and GPU memory to facilitate efficient transfers. Cover bidirectional patterns: passing data from CPU to GPU for processing, collecting results back to CPU, and iterative refinement. Explain pinned memory allocation: how to identify which CPU memory should be pinned for faster GPU access. Discuss the tradeoff: pinned memory is a limited resource (reducing available pageable RAM). Explain how to structure computations for high GPU utilization despite CPU-GPU communication: computing while transfers happen, prefetching next data while processing current data. Discuss applications: interactive workloads, reinforcement learning environments, sensor data processing. Include profiling and measurement: understanding where time is spent in CPU-GPU communication. Discuss advanced techniques: peer access between GPUs, and unified virtual addressing. Finally, include practical recommendations for structuring applications to minimize CPU-GPU communication overhead."""
]

# Create a sampling params object.
sampling_params = SamplingParams(temperature=0.8, top_p=0.95, max_tokens=512)


def main():
    if enable_builtin_profiling:
        profiler_config = dict(
            profiler="torch",
            torch_profiler_dir="./vllm_profile",
            torch_profiler_with_flops=True,
            torch_profiler_record_shapes=True,
            torch_profiler_with_memory=True,
        )
    else:
        profiler_config = None

    # Create an LLM.
    llm = LLM(
        model="deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
        tensor_parallel_size=2,
        pipeline_parallel_size=1,
        profiler_config=profiler_config,
        enable_layerwise_nvtx_tracing=True,
        kv_cache_metrics=True,
        enforce_eager=True,
        max_num_seqs=8,
        enable_prefix_caching=False,
    )

    if enable_builtin_profiling:
        llm.start_profile()

    # Generate texts from the prompts. The output is a list of RequestOutput
    # objects that contain the prompt, generated text, and other information.
    outputs = llm.generate(prompts, sampling_params)

    if enable_builtin_profiling:
        llm.stop_profile()

    # Print the outputs.
    print("-" * 50)
    for output in outputs:
        prompt = output.prompt
        generated_text = output.outputs[0].text
        print(f"Prompt: {prompt!r}\nGenerated text: {generated_text!r}")
        print("-" * 50)

    # Add a buffer to wait for profiler in the background process
    # (in case MP is on) to finish writing profiling output.
    time.sleep(10)


if __name__ == "__main__":
    main()
